import React, { useEffect } from "react";
import { useSignInWithGoogle } from "react-firebase-hooks/auth";
import { useRouter } from "next/router";
import Head from "next/head";
import { motion } from "framer-motion";
import { useAuthState } from "react-firebase-hooks/auth";

import { auth } from "../../firebase/firebase";

type SignInProps = {};

const SignIn: React.FC<SignInProps> = () => {
  const router = useRouter();
  const [user] = useAuthState(auth);
  const [signInWithGoogle, userCred, loading, error] =
    useSignInWithGoogle(auth);

  const handleSignUp = async () => {
    signInWithGoogle();
  };

  useEffect(() => {
    if (user) {
      router.push("/");
    } else {
      console.log("You Need To Login");
    }
  }, [user]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/1200px-Twitter-logo.svg.png"
        />
      </Head>
      <div className="flex flex-col items-center justify-center min-h-screen py-2 -mt-56 px-14 text-center pt-60">
        <img
          //className="h-120"
          style={{ height: "400px" }}
          src="https://cutewallpaper.org/24/logo-de-twitter-png/logotipo-twitter-en-png-y-vector-ai-descarga-el-logo-de-twitter.png"
          alt=""
        />
        <p className="font-xs italic">
          This is not a Real app, it is build for educational purpose only
        </p>
        <div className="mt-20">
          <div>
            <button
              className="p-3 bg-twitter rounded-lg text-white font-bold hover:bg-gray-500"
              onClick={handleSignUp}
            >
              Sign in with Google
            </button>
          </div>
        </div>
      </div>
    </motion.div>
  );
};
export default SignIn;
