import { GetServerSideProps } from "next";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Feed from "../components/Feed";
import SideBar from "../components/SideBar";
import Widgets from "../components/Widgets";
import { Tweet } from "../typings";
import { fetchTweet } from "../utils/fetchTweet";

interface Props {
  tweets: Tweet[];
}

const Home = ({ tweets }: Props) => {
  //console.log(tweets, "🚀🚀");
  return (
    <div className="mx-auto max-h-screen overflow-hidden lg:max-w-6xl">
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Twitter-logo.svg/1200px-Twitter-logo.svg.png"
        />
      </Head>
      <Toaster />
      <main className="grid grid-cols-9">
        <SideBar />
        <Feed tweets={tweets} />
        <Widgets />
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
  const tweets = await fetchTweet();

  return {
    props: {
      tweets,
    },
  };
};
